language: node_js
notifications:
  email: false

stages:
  - test
  - deploy

jobs:
  include:
  - stage: deploy
    node_js: 10
    script: skip
    deploy:
      provider: script
      skip_cleanup: true
      script: npm run deploy

env:
  global:
  - FORCE_COLOR=1
  - NPM_CONFIG_COLOR=always
  - secure: KWfKLRR2HOCeGOjahD29WQrCvwU3jln1LlEyp0n2mcEO3SmVScPWPemuWXq5XRGd5AUNljWfFILKcw4YI4qhIpqNcbfNYti1L5ifgyTatb4mQEDUQ4MkJvlM3HvTtcdiuW79/sev6kBeGEofMm2pWB5NY4BFQbKZJOW8zr/OQ9I4NrI6N4pa6a3SuiZ3cbwC4irfBvmqWu3nXL5COUlA54+ulHqH/JfzxdJxfjBh3nSU5MGHQDWPCVg83uGeZCvKJzLKmObKqLrtfekQ4MZNIjariwrokZ+1pInS3zV2xRukCuNS1O98h0l1FJAjFA3zTR+oDdShokzom5bdj1+1oQG/zX3iqIZ8uBTZ/TUyFbrUm5OGv5IcTJfLfh+IYKf9cnZVKlbpPKh332WsciywsZiGHmDZXMUnrFf0eL6HAtxI0PxqaIpRE+minhWN6Ek1/BQXdoc8gf7RictJ8US329Ru8haShe6JK3VHDmccPeE6IYKrpbRvjzJx6uWpIGNJo/Q8YGyaVzile9pk+B8RP09T6hXSQFd5w2Ly8KT3fDgrpM7XMGn5Vkzk/eOR631ZAaXJ4buq1FBt0FlIpAr63aVXM1NGsGrS9htdwAHgf6Es1bWTWlyEGVBpHCV0YMm354tRORGjg6Z/11XOrMa7i9yYxm664P1xBRIK48qPRPE=
